name: splash
description: Splash feature
version: 0.0.1
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  common_dependencies:
    path: ../../infrastructure/common_dependencies/
  core:
    path: ../../infrastructure/core/

  ## Libraries
  faker: ^2.0.0

flutter:
  uses-material-design: true
