name: login
description: Login feature
version: 0.0.1
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  common_dependencies:
    path: ../../infrastructure/common_dependencies/
  core:
    path: ../../infrastructure/core/

  ## Libraries

dev_dependencies:
  build_runner: ^2.0.4
  freezed: ^0.14.2

flutter:
  uses-material-design: true
  assets:
    - assets/i18n/
